# Generated by Django 3.2.12 on 2022-11-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment_details',
            fields=[
                ('allot_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('curr_loc', models.IntegerField()),
                ('prev_loc', models.IntegerField()),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working')], max_length=50)),
                ('remarks', models.TextField()),
                ('allot_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingMaster',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=250)),
                ('entry_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypeMaster',
            fields=[
                ('product_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type_name', models.CharField(max_length=250)),
                ('entry_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('post', models.TextField()),
                ('mobileno', models.IntegerField()),
                ('entry_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Section_details',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.TextField()),
                ('roomno', models.TextField()),
                ('section_name', models.TextField()),
                ('entry_date', models.DateTimeField()),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einventoryAPI.buildingmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_model', models.TextField()),
                ('product_serialno', models.TextField()),
                ('product_notsheet_no', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entry_date', models.DateTimeField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einventoryAPI.producttypemaster')),
            ],
        ),
    ]
