# Generated by Django 3.2.12 on 2022-11-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einventoryAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment_details',
            name='allot_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='buildingmaster',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='producttypemaster',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='section_details',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
