# Generated by Django 3.2.12 on 2022-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einventoryAPI', '0002_auto_20221126_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment_details',
            name='remarks',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_model',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_notsheet_no',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_serialno',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='section_details',
            name='floor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='section_details',
            name='roomno',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='section_details',
            name='section_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='post',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user_name',
            field=models.CharField(max_length=250),
        ),
    ]
